#######################################################################################
## DataSourceDefinition                             
#######################################################################################
apiVersion: v0.1
kind: DataSourceDefinition
metadata:
  id: batteryPercentage
  scope: ""
spec:
  label: Battery Percentage
  source:
    keyValue:
      key: "battery_percentage"
  timeline: {}
---
apiVersion: v0.1
kind: DataSourceDefinition
metadata:
  id: batteryVoltage
  scope: ""
spec:
  label: Battery Voltage
  source:
    keyValue:
      key: "battery_voltage"
  timeline: {}
---
apiVersion: v0.1
kind: DataSourceDefinition
metadata:
  id: batteryCharging
  scope: ""
spec:
  label: Battery Voltage
  source:
    keyValue:
      key: "battery_charging"
---
#######################################################################################
## DashboardDefinition
#######################################################################################
apiVersion: v0.1
kind: DashboardDefinition
metadata:
  id: welcome
  scope: ''
spec:
  label: Welcome
  order: 0
  sections:
  - label: ''
    scope: robot
    withControlWidget: false
    widgets:
    - type: text
      label: Guide
      config: 
        text: |
          # OpenRobOps

          Welcome to your first OpenRobOps dashboard.

          OpenRobOps (ORO) is an open-source robot fleet management and operations platform. 
          It provides real-time observability, monitoring, and control for autonomous mobile robots (AMRs) — fully self-hostable, with native support for ROS and Open RMF.
          Learn more on [https://openrobops.org/](https://openrobops.org/).
          
          ## Dashboards

          This demonstration instance is set up with a simulated robots you can monitor and operate through the widgets provided in these dashboards:
           - [Fleet](/dashboards/fleet): Overview of all robots in the fleet, their status and fleet-level diagnostics
           - [Robot](/dashboards/robot): Detailed view of a single robot, including its health, telemetry, reported data, and actions
           - [Navigation](/dashboards/navigation): Real-time navigation status and controls

          ## Simulation

          The simulated robot `flatland-sim` is a simple 2D simulation running [ROS2](https://www.ros.org/). 
          It implements the [Flatland](https://github.com/avidbots/flatland) simulator and the [Nav2](https://github.com/ros-planning/navigation2) navigation stack,
          providing a realistic simulation of the robot's behavior and navigation. 
          It also implements a battery plugin that simulates the robot's battery state, which drains rather quickly for demo purposes, and recharges when
          the robot enters a charging zone.


          The map consists of four offices and a central corridor. 
          There are two charging zones, in offices "A" (top-left) and "D" (bottom-right). 

          Currently the robot accepts the following commands:
          - Dock:
            - **Dock A**, **Dock D**: Navigates to the charging zones in office "A" or "D" respectively.
            - **Dock (nearest)**: Goes to the nearest charging zone.
          - Battery:
            - **Reset** Replaces the battery to 100%.
            - **Charging** and **Discharging** toggles the charging state.

          Additionally, the robot reports key-value pairs as custom data elements, including `battery_percentage` and `battery_voltage` for battery
          state, and  `estimated_time_remaining` from the nav2 stack. These are added to other built-in attributes implemented by the agent 
          such as CPU usage, disk usage, network rate, etc.

          This simulation is available on [Github](https://github.com/OpenRobOps/sim-flatland) to be used as a ready-to-run docker environment
          which includes the ORO agent as a sidecar, ready to connect to OpenRobOps.

      layout:
        chroma: false
        grid: 12
        height: 3
---    
apiVersion: v0.1
kind: DashboardDefinition
metadata:
  id: robot
  scope: ''
spec:
  label: Robot
  order: 2
  sections:
  - label: Health
    withControlWidget: true
    scope: robot
    widgets:
    - config:
        dataSources:
        - id: cpuLoadPercentage
          label: CPU usage
          type: gauge
          unit: '%'
        - id: diskUsagePercentage
          label: Disk usage
          type: gauge
          unit: '%'
        - id: batteryPercentage
          label: Battery
          type: gauge
          unit: '%'
        - id: networkOroRate
          label: Agent network rate
          type: gauge
          unit: kbps
      label: Vitals
      layout:
        chroma: true
        grid: 4
        height: 1
      type: vitals
    - label: Data Sources
      type: listData
      layout:
        chroma: true
        grid: 4
        height: 1
      config:
        dataSources:
        - id: batteryCharging
          label: Charging state
          type: boolean
        - id: batteryVoltage
          label: Battery voltage (V)
          unit: V
          type: text
        - id: batteryPercentage
          label: Battery percentage
          unit: "%"
          type: text
    - label: Key Value pairs
      type: keyValues
      layout:
        chroma: true
        grid: 4
        height: 1
    - type: chart
      label: Battery
      config:
        chartType: linechart
        dataSources:
        - id: batteryPercentage
          label: Batt %
          precision: 1
          scale: 100
        - id: batteryVoltage
          label: Batt V
          precision: 2
          scale: 1
        max: 120
        min: 0
      layout:
        chroma: true
        grid: 8
        height: 1
    - type: diagnostics
      label: Diagnostics
      layout:
        chroma: true
        height: 1
    - type: chart
      label: System
      config:
        chartType: linechart
        dataSources:
        - id: cpuLoadPercentage
          label: CPU
          precision: 0
          scale: 100
        - id: ramUsagePercentage
          label: RAM
          precision: 0
          scale: 1
        max: 120
        min: 0
      layout:
        chroma: true
        grid: 8
        height: 1
---
apiVersion: v0.1
kind: DashboardDefinition
metadata:
  id: ops
  scope: ''
spec:
  label: Ops
  order: 3
  sections:
  - label: Health
    withControlWidget: true
    scope: robot
    widgets:
    - config: {}
      label: Actions
      layout:
        chroma: true
        grid: 4
        height: 1
      type: actionsWidget
    - type: cameraWidget
      label: Front camera
      config: 
        cameraId: "0"
      layout: 
        chroma: true
        grid: 4
        height: 1
    - type: diagnostics
      label: Diagnostics
      layout:
        chroma: true
        height: 1
---
apiVersion: v0.1
kind: DashboardDefinition
metadata:
  id: navigation
  scope: ''
spec:
  label: Navigation
  order: 4
  sections:
  - label: Robot Navigation
    withControlWidget: false
    scope: navigation
    widgets:
    - label: Navigation
      layout:
        grid: 12
        height: 2
      type: navigation
    withControlWidget: true
---
#######################################################################################
## ActionDefinition
#######################################################################################
apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: BatteryReset
  scope: ''
spec:
  label: Reset
  group: Battery
  type: PublishToTopic
  arguments:
  - name: message
    value: reset
  description: 'Reset battery to 100%'
  lock: true
---
apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: BatteryDischarge
  scope: ''
spec:
  label: Discharging
  group: Battery
  type: PublishToTopic
  arguments:
  - name: message
    value: discharge
  description: 'Start discharging'
  lock: true
---
apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: BatteryCharge
  scope: ''
spec:
  label: Charging
  group: Battery
  type: PublishToTopic
  arguments:
  - name: message
    value: charge
  description: 'Start charging'
  lock: true    
---
apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: DockAuto
  scope: ''
spec:
  label: Dock (nearest)
  group: Dock
  type: PublishToTopic
  arguments:
  - name: message
    value: dock
  description: 'Go to nearest charger'
  lock: true      
  widgets:
  - navigation
---
apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: DockA
  scope: ''
spec:
  label: Dock A
  group: Dock
  type: PublishToTopic
  arguments:
  - name: message
    value: dock=A
  description: 'Go to Charger A'
  lock: true      
  widgets:
  - navigation
---
apiVersion: v0.1
kind: ActionDefinition
metadata:
  id: DockD
  scope: ''
spec:
  label: Dock D
  group: Dock
  type: PublishToTopic
  arguments:
  - name: message
    value: dock=D
  description: 'Go to Charger D'
  lock: true      
  widgets:
  - navigation
---
#######################################################################################
## ModuleState
#######################################################################################
# CustomDataAgentlet: Startup defaults are fine
# RosMapAgentlet, RosPoseAgentlet: Startup defaults are fine (just runlevel)
# RosImageAgentlet: Startup defaults should be fine (to be tested - flatland does not have images)
# RosLocalizationAgentlet: This is where most flatland topics need to be configured. Also enable it by default, runLevel 5 (it is the default, don't forget to keep this setting)
apiVersion: v0.1
kind: ModuleState
metadata:
  id: RosLocalizationAgentlet
  scope: ''
spec:
  state:
    minRunlevel: 5
    map_topic: "map"
    nav_goal_topic: "goal_pose"
    laser_topic: "scan"
    costmap_topic: "local_costmap/costmap"
    set_pose_topic: "flatland_0/initialpose"
    path_topics: 
     "0": { "topic": "plan"}
---
# RosTeleopAgentlet: Set the cmd_vel topic
apiVersion: v0.1
kind: ModuleState
metadata:
  id: RosTeleopAgentlet
  scope: ''
spec:
  state:
    publish_zero_vel: true
    cmd_vel_topic: "flatland_0/cmd_vel"

# RosImageAgentlet: Set the image topic
apiVersion: v0.1
kind: ModuleState
metadata:
  id: RosImageAgentlet
  scope: ''
spec:
  state:
    camera_topics:
      0: "image_raw/compressed"
    cameraViewOn: true
    cameras_config: 
      0: 
        output_encoding: 'mono8'
        quality: 50
        rate: 2
        img_width: 320
        img_height: 240
        is_on: true
