apiVersion: v0.1
kind: DashboardDefinition
metadata:
  id: test
  scope: ""
spec:
  label: Timeline
  sections:
  - label: Fleet
    scope: fleet
    widgets:
    - type: incidentTimeline
      label: Incidents
      config: {}
      layout: 
        grid: 12
  # - label: Details
  #   scope: robot
  #   widgets:
  #   - config:
  #       chartType: areachart
  #       dataSources:
  #       - id: batteryPercentage
  #         label: Batt %
  #         precision: 1
  #         scale: 100
  #       - id: batteryVoltage
  #         label: Batt V
  #         precision: 2
  #         scale: 1
  #         op: maximum
  #       max: 200
  #       min: 0
  #     label: Timeline
  #     layout:
  #       chroma: true
  #       grid: 8
  #       height: 1
  #     type: chart

